version = 0.1

[default.deploy.parameters]
stack_name = "zoolanding-config-authoring"
resolve_s3 = true
s3_prefix = "zoolanding-config-authoring"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "ConfigTableName=zoolanding-config-registry",
  "ConfigPayloadsBucketName=zoolanding-config-payloads",
  "LogLevel=INFO"
]

[dev.deploy.parameters]
stack_name = "zoolanding-config-authoring-dev"
resolve_s3 = true
s3_prefix = "zoolanding-config-authoring-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "EnvironmentName=dev",
  "ManageStorageResources=true",
  "ConfigTableName=zoolanding-config-registry-dev",
  "ConfigPayloadsBucketName=zoolanding-config-payloads-dev",
  "LogLevel=INFO"
]

[test.deploy.parameters]
stack_name = "zoolanding-config-authoring-test"
resolve_s3 = true
s3_prefix = "zoolanding-config-authoring-test"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "EnvironmentName=test",
  "ManageStorageResources=true",
  "ConfigTableName=zoolanding-config-registry-test",
  "ConfigPayloadsBucketName=zoolanding-config-payloads-test",
  "LogLevel=INFO"
]

[prod.deploy.parameters]
stack_name = "zoolanding-config-authoring"
resolve_s3 = true
s3_prefix = "zoolanding-config-authoring"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "EnvironmentName=prod",
  "ManageStorageResources=false",
  "ConfigTableName=zoolanding-config-registry",
  "ConfigPayloadsBucketName=zoolanding-config-payloads",
  "LogLevel=INFO"
]
